name: CI/CD Workflow

on:
  push:
    branches:
      - bharath
  pull_request:
    branches:
      - bharath

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - AdminModule-EKA
          - AnnouncementsModule
          - Attendance_01
          - AuthService
          - DocumentsModule
          - Eureka_EKA
          - Gateway_EKA-1
          - GitConfiguration-Eka
          - PaymentModule
          - RequestsAndComplaints

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Specify the Java version if needed
          distribution: 'adoptopenjdk'

      - name: Install dependencies and build
        run: |
          cd ${{ matrix.module }}
          ./mvnw clean install  # Use `./gradlew build` if using Gradle

      - name: Run tests
        run: |
          cd ${{ matrix.module }}
          ./mvnw test  # Use `./gradlew test` if using Gradle

      - name: Package module
        run: |
          cd ${{ matrix.module }}
          ./mvnw package  # Use `./gradlew build` if using Gradle

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy modules
        run: |
          for module in AdminModule-EKA AnnouncementsModule Attendance_01 AuthService DocumentsModule Eureka_EKA Gateway_EKA-1 GitConfiguration-Eka PaymentModule RequestsAndComplaints; do
            echo "Deploying $module"
            cd $module
            # Add your deployment commands here
            # Example: ./deploy.sh
            cd ..
          done
